name: "Multi-Cloud Terraform CI/CD"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  id-token: write   # Required for requesting the JWT from GitHub OIDC
  contents: read     # Required for actions/checkout
  issues: write 
  pull-requests: write  

env:
  # AWS OIDC Configuration
  AWS_REGION: "us-east-1"
  AWS_ROLE_TO_ASSUME: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-terraform-eks"
  TF_WORKSPACE: "default"
  CONFIG_DIRECTORY: "./environments/dev/aws/compute"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  TF_VAR_AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      
      # Pass the non-sensitive configuration parameters directly
  TF_VAR_instance_count: 1
  TF_VAR_environment: "dev"
  TF_VAR_region: "us-east-1"
  TF_VAR_availability_zones: '["us-east-1a", "us-east-1b", "us-east-1c"]'  
  TF_VAR_github_repo_url: "https://github.com/harshikab/web-app.git"
  TF_VAR_github_runner_token: "{{ secrets.GH_RUNNER_TOKEN }}"



  #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # Azure OIDC Configuration (Read natively by the azurerm provider)
  #ARM_USE_OIDC: "true"
  #ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
 # ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code
    - name: Checkout Source Code
      uses: actions/checkout@v4

    # 2. Authenticate to AWS via OIDC
    - name: Configure AWS Credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ env.AWS_REGION }}
        audience: sts.amazonaws.com

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.10.0"

    # 4. Check Code Formatting
    - name: Terraform Format Check
      working-directory: ${{ env.CONFIG_DIRECTORY }}
      run: terraform fmt -check

    # 5. Initialize Backend and Providers
    - name: Terraform Init
      working-directory: ${{ env.CONFIG_DIRECTORY }}
      run: terraform init

    # 6. Run Security Scan (Static Analysis)
    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        hide-progress: true
        format: 'table'
        exit-code: '0' # Set to 1 if you want to block the pipeline on security failures
    
    - name : Run Checkov Static Code Analysis
      uses: bridgecrewio/checkov-action@master
      with:
        directory: './environments/dev/aws/compute' # Path to your Terraform code
        framework: 'terraform'
        soft_fail: true # Set to true if you want to allow failures without blocking the pipeline

    - name: TruffleHog OSS 
      id: trufflehog 
      uses: trufflesecurity/trufflehog@v3.0.0
      continue-on-error: true 
      with: 
        path: ./ 
        base: "${{ github.event.repository.default_branch }}" 
        head: HEAD 
        extra_args: --debug --only-verified 
    
    - name: Scan for Secrets
      id: trufflehog-secrets
      if: steps.trufflehog.outcome == 'failure' 
      run: exit 0

# 1. Install the standard Terraform CLI on the runner
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}


    # 3. Run the plan directly on the runner hardware
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      working-directory: ${{ env.CONFIG_DIRECTORY }}


    # 8. Apply Changes (Only on merge/push to main branch)
    #- name: Terraform Apply
    #  if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #  run: terraform apply -auto-approve -input=false